name: Build and Release

on:
  push:
    tags:
      - '*.*.*.*'
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          choco install conan -y --force
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Start-Sleep -Seconds 5
          conan --version
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja
        shell: powershell

      - name: Conan setup
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Start-Sleep -Seconds 5
          conan --version
          conan profile detect
          $profilePath = "$env:USERPROFILE\.conan2\profiles\default"
          Set-Content -Path $profilePath -Value @"
            [settings]
            os=Windows
            arch=x86_64
            compiler=msvc
            compiler.version=193
            compiler.cppstd=23
            build_type=Release
          "@
          conan profile show
        shell: powershell

      - name: Run Conan install
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Start-Sleep -Seconds 5
          conan --version
          conan install . --build=missing -s compiler.runtime=dynamic
        shell: powershell

      - name: Build with CMake
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Start-Sleep -Seconds 5
          cmake -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH=build\generators -A x64 -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --config Release
        shell: powershell

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: Release\Ciple-Framework.exe
          tags: false
          draft: false
  build-and-release-linux:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          cmake \
          g++ \
          ninja-build \
          && sudo rm -rf /var/lib/apt/lists/*
      - name: Download Conan & reqs
        working-directory: .
        run: |
          sudo wget https://github.com/conan-io/conan/releases/download/2.8.0/conan-2.8.0-amd64.deb && sudo dpkg -i conan-2.8.0-amd64.deb
          sudo conan profile detect && sudo conan install . --build=missing
      - name: Build with Cmake
        working-directory: .
        run: |
          sudo cmake -G Ninja -DCMAKE_PREFIX_PATH=build/Release/generators  -DCMAKE_BUILD_TYPE=Release .
          sudo cmake --build . --config Release
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: Ciple-Framework
          tags: false
          draft: false